### ISSUE TITLE
Cannot select text and move cursor down to scroll down and select more.

### ISSUE THREAD

**Issue by BC-548** [schooltape-community/schooltape#21]
**Description**
When something is selected, one cannot select more text that is not currently in the window by holding and moving the cursor down to the bottom of the window.

You can select upwards, but not downwards.

**To Reproduce**
1. Select some text
2. Move cursor down to select text currently not visible in the window
3. Notice how the page does not scroll down with the cursor to select more text

**Expected behavior**
The page should scroll down as you move the cursor to select more past the bottom of the window.

**Comment by 42Willow** [comment]
I don't know how to fix this, if you figure it out please let me know. Thank you.
